<x-app-layout>
    <x-slot name="header">
        <div><h1 class="text-2xl font-semibold text-gray-900">Reportes</h1><p class="mt-1 text-sm text-gray-600">Ventas confirmadas de {{ $periodLabel }}.</p></div>
    </x-slot>

    <div class="py-8"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8">
        @if ($errors->any())
            <div class="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800" role="alert"><p class="font-semibold">Revisa el período seleccionado.</p><ul class="mt-1 list-disc pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>
        @endif

        <section aria-labelledby="period-title">
            <div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 id="period-title" class="text-lg font-semibold text-gray-900">Seleccionar período</h2><p class="text-sm text-gray-500">Elige una de las tres formas de consulta.</p></div>
                @can('export', \App\Models\Sale::class)<a href="{{ route('reports.pdf', $filters) }}" class="inline-flex items-center justify-center rounded-lg bg-red-700 px-5 py-3 text-base font-semibold text-white shadow-sm hover:bg-red-800">Descargar PDF</a>@endcan
            </div>
            <div class="mt-4 grid gap-4 lg:grid-cols-3">
                <article class="rounded-xl border border-indigo-200 bg-white p-5 shadow-sm"><h3 class="text-base font-semibold text-indigo-900">Reporte por día</h3><p class="mt-1 text-sm text-gray-500">Hoy, ayer o una fecha específica.</p><div class="mt-4 grid grid-cols-2 gap-3"><a href="{{ route('reports.index', ['period' => 'today']) }}" class="inline-flex min-h-11 items-center justify-center rounded-lg px-4 py-2.5 text-base font-semibold {{ $filters['period'] === 'today' ? 'bg-indigo-600 text-white' : 'bg-gray-100 text-gray-700 hover:bg-gray-200' }}">Hoy</a><a href="{{ route('reports.index', ['period' => 'yesterday']) }}" class="inline-flex min-h-11 items-center justify-center rounded-lg px-4 py-2.5 text-base font-semibold {{ $filters['period'] === 'yesterday' ? 'bg-indigo-600 text-white' : 'bg-gray-100 text-gray-700 hover:bg-gray-200' }}">Ayer</a></div><form method="GET" class="mt-3 grid gap-2 sm:grid-cols-[1fr_auto]"><input type="hidden" name="period" value="date"><label><span class="mb-1 block text-xs font-medium text-gray-600">Fecha específica</span><input type="date" name="date" value="{{ $filters['date'] }}" class="w-full rounded-md border-gray-300 text-base" required></label><button class="self-end rounded-md bg-gray-800 px-4 py-2.5 text-base font-semibold text-white">Consultar</button></form></article>
                <article class="rounded-xl border border-emerald-200 bg-white p-5 shadow-sm"><h3 class="text-base font-semibold text-emerald-900">Reporte por rango</h3><p class="mt-1 text-sm text-gray-500">Incluye las fechas inicial y final.</p><form method="GET" class="mt-4 grid grid-cols-2 gap-3"><input type="hidden" name="period" value="range"><label><span class="mb-1 block text-xs font-medium text-gray-600">Fecha inicial</span><input type="date" name="start" value="{{ $filters['start'] }}" class="w-full rounded-md border-gray-300 text-base" required></label><label><span class="mb-1 block text-xs font-medium text-gray-600">Fecha final</span><input type="date" name="end" value="{{ $filters['end'] }}" class="w-full rounded-md border-gray-300 text-base" required></label><button class="col-span-2 rounded-md bg-gray-800 px-4 py-2.5 text-base font-semibold text-white">Consultar rango</button></form></article>
                <article class="rounded-xl border border-violet-200 bg-white p-5 shadow-sm"><h3 class="text-base font-semibold text-violet-900">Reporte mensual</h3><p class="mt-1 text-sm text-gray-500">Consulta todas las ventas de un mes.</p><form method="GET" class="mt-4 space-y-3"><input type="hidden" name="period" value="month"><label><span class="mb-1 block text-xs font-medium text-gray-600">Mes</span><input type="month" name="month" value="{{ $filters['month'] }}" class="w-full rounded-md border-gray-300 text-base" required></label><button class="w-full rounded-md bg-gray-800 px-4 py-2.5 text-base font-semibold text-white">Consultar mes</button></form></article>
            </div>
        </section>

        <section aria-labelledby="summary-title"><div class="mb-3"><h2 id="summary-title" class="text-lg font-semibold text-gray-900">Resumen del período</h2><p class="text-sm text-gray-500">{{ $periodLabel }}</p></div>
            <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
                <div class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-gray-200"><p class="text-sm font-medium text-gray-500">Ventas confirmadas</p><p class="mt-2 text-3xl font-bold text-gray-900">{{ $salesCount }}</p><p class="mt-1 text-sm text-gray-600">Bs {{ number_format((float) $salesTotal, 2, ',', '.') }} vendidos</p></div>
                <div class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-gray-200"><p class="text-sm font-medium text-gray-500">Efectivo recibido</p><p class="mt-2 text-3xl font-bold text-emerald-700">Bs {{ number_format((float) $cashTotal, 2, ',', '.') }}</p><p class="mt-1 text-sm text-gray-600">{{ $cashCount }} {{ $cashCount === 1 ? 'operación' : 'operaciones' }} con efectivo</p></div>
                <div class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-gray-200"><p class="text-sm font-medium text-gray-500">Pagos QR</p><p class="mt-2 text-3xl font-bold text-cyan-700">Bs {{ number_format((float) $qrTotal, 2, ',', '.') }}</p><p class="mt-1 text-sm text-gray-600">{{ $qrCount }} {{ $qrCount === 1 ? 'operación' : 'operaciones' }} con QR</p></div>
                <div class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-gray-200"><p class="text-sm font-medium text-gray-500">Pagos mixtos</p><p class="mt-2 text-3xl font-bold text-violet-700">{{ $mixedCount }}</p><p class="mt-1 text-sm text-gray-600">Bs {{ number_format((float) $mixedTotal, 2, ',', '.') }} en ventas mixtas</p></div>
            </div>
        </section>

        <section class="overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-gray-200" aria-labelledby="chart-title">
            <div class="border-b p-5"><h2 id="chart-title" class="font-semibold text-gray-900">{{ $chartData['title'] }}</h2><p class="mt-1 text-sm text-gray-500">Compara la cantidad de ventas y el monto vendido en cada {{ $chartData['interval'] === 'hour' ? 'hora' : 'día' }}.</p></div>
            <div class="overflow-x-auto p-4 sm:p-5">@include('reports.partials.chart-svg', ['chart' => $chartData, 'forPdf' => false])</div>
        </section>

        @if ($dailySummary->count() > 1 || $filters['period'] === 'month')
            <section class="overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-gray-200" aria-labelledby="daily-title"><div class="border-b p-5"><h2 id="daily-title" class="font-semibold text-gray-900">Resumen por día</h2></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200"><thead class="bg-gray-50"><tr><th class="px-5 py-3 text-left text-xs font-semibold uppercase text-gray-500">Día</th><th class="px-5 py-3 text-right text-xs font-semibold uppercase text-gray-500">Ventas</th><th class="px-5 py-3 text-right text-xs font-semibold uppercase text-gray-500">Total</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse ($dailySummary as $day)<tr><td class="px-5 py-3 text-sm text-gray-700">{{ \Carbon\Carbon::parse($day->day)->format('d/m/Y') }}</td><td class="px-5 py-3 text-right font-medium">{{ $day->sales_count }}</td><td class="px-5 py-3 text-right font-semibold">Bs {{ number_format((float) $day->total, 2, ',', '.') }}</td></tr>@empty<tr><td colspan="3" class="p-8 text-center text-sm text-gray-500">No existen ventas confirmadas en este mes.</td></tr>@endforelse</tbody></table></div></section>
        @endif

        <section class="overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-gray-200" aria-labelledby="products-title"><div class="border-b p-5"><h2 id="products-title" class="font-semibold text-gray-900">Productos vendidos</h2><p class="text-sm text-gray-500">Nombre y unidad conservados desde cada venta.</p></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200"><thead class="bg-gray-50"><tr><th class="px-5 py-3 text-left text-xs font-semibold uppercase text-gray-500">Producto</th><th class="px-5 py-3 text-right text-xs font-semibold uppercase text-gray-500">Cantidad</th><th class="px-5 py-3 text-right text-xs font-semibold uppercase text-gray-500">Importe generado</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse ($products as $product)<tr><td class="px-5 py-3 font-medium text-gray-900">{{ $product->product_name }}</td><td class="px-5 py-3 text-right text-gray-700">{{ $product->quantity_display }}</td><td class="px-5 py-3 text-right font-semibold text-gray-900">Bs {{ number_format((float) $product->amount_generated, 2, ',', '.') }}</td></tr>@empty<tr><td colspan="3" class="p-8 text-center text-sm text-gray-500">No se vendieron productos durante este período.</td></tr>@endforelse</tbody></table></div></section>

        <section aria-labelledby="sales-title"><div class="mb-3 flex items-end justify-between"><div><h2 id="sales-title" class="text-lg font-semibold text-gray-900">Detalle de ventas</h2><p class="text-sm text-gray-500">Solo ventas confirmadas.</p></div></div>
            <div class="hidden overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-gray-200 lg:block"><table class="min-w-full divide-y divide-gray-200"><thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left text-xs font-semibold uppercase text-gray-500">Venta</th><th class="px-4 py-3 text-left text-xs font-semibold uppercase text-gray-500">Fecha y hora</th><th class="px-4 py-3 text-left text-xs font-semibold uppercase text-gray-500">Cajero</th><th class="px-4 py-3 text-left text-xs font-semibold uppercase text-gray-500">Pago</th><th class="px-4 py-3 text-right text-xs font-semibold uppercase text-gray-500">Total</th><th class="px-4 py-3 text-left text-xs font-semibold uppercase text-gray-500">Estado</th><th class="px-4 py-3"></th></tr></thead><tbody class="divide-y divide-gray-100">@forelse ($sales as $sale)<tr><td class="px-4 py-3 font-medium">{{ $sale->sale_number }}</td><td class="whitespace-nowrap px-4 py-3 text-sm">{{ $sale->confirmed_at->format('d/m/Y H:i') }}</td><td class="px-4 py-3 text-sm">{{ $sale->user->name }}</td><td class="px-4 py-3 text-sm">{{ $sale->paymentLabel() }}</td><td class="px-4 py-3 text-right font-semibold">Bs {{ number_format((float) $sale->total, 2, ',', '.') }}</td><td class="px-4 py-3 text-sm">{{ $sale->status->label() }}</td><td class="px-4 py-3 text-right"><a href="{{ route('sales.show', $sale) }}" class="text-sm font-semibold text-indigo-600">Ver detalle</a></td></tr>@empty<tr><td colspan="7" class="p-8 text-center text-sm text-gray-500">No existen ventas confirmadas en el período seleccionado.</td></tr>@endforelse</tbody></table></div>
            <div class="space-y-4 lg:hidden">@forelse ($sales as $sale)<article class="rounded-xl bg-white p-4 shadow-sm ring-1 ring-gray-200"><div class="flex justify-between gap-3"><div><h3 class="font-semibold text-gray-900">{{ $sale->sale_number }}</h3><p class="text-xs text-gray-500">{{ $sale->confirmed_at->format('d/m/Y H:i') }}</p></div><span class="font-bold text-gray-900">Bs {{ number_format((float) $sale->total, 2, ',', '.') }}</span></div><dl class="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt class="text-gray-500">Cajero</dt><dd>{{ $sale->user->name }}</dd></div><div><dt class="text-gray-500">Pago</dt><dd>{{ $sale->paymentLabel() }}</dd></div><div><dt class="text-gray-500">Estado</dt><dd>{{ $sale->status->label() }}</dd></div><div class="text-right"><a href="{{ route('sales.show', $sale) }}" class="font-semibold text-indigo-600">Ver detalle</a></div></dl></article>@empty<div class="rounded-xl bg-white p-8 text-center text-sm text-gray-500 shadow-sm ring-1 ring-gray-200">No existen ventas confirmadas en el período seleccionado.</div>@endforelse</div>
            <div class="mt-6">{{ $sales->links() }}</div>
        </section>
    </div></div>

</x-app-layout>
