<x-app-layout>
    <x-slot name="header"><h1 class="text-2xl font-semibold text-gray-900">Registrar movimiento</h1><p class="mt-1 text-sm text-gray-600">{{ $product->name }} · {{ $product->displayCode() }}</p></x-slot>
    <div class="py-8"><div class="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
        <div class="mb-6 grid gap-3 rounded-xl bg-white p-4 shadow-sm ring-1 ring-gray-200 sm:grid-cols-3"><div><div class="text-xs uppercase text-gray-500">Stock actual</div><div class="mt-1 text-xl font-semibold text-gray-900">{{ $product->unit->formatQuantity($product->stock) }}</div></div><div><div class="text-xs uppercase text-gray-500">Unidad</div><div class="mt-1 font-medium text-gray-900">{{ $product->unit->label() }}</div></div><div><div class="text-xs uppercase text-gray-500">Categoría</div><div class="mt-1 font-medium text-gray-900">{{ $product->category->name }}</div></div></div>
        <form method="POST" action="{{ route('inventory.movements.store', $product) }}" class="space-y-6 rounded-xl bg-white p-5 shadow-sm ring-1 ring-gray-200 sm:p-8">@csrf
            <div class="grid gap-6 sm:grid-cols-2"><div><x-input-label for="type" value="Tipo de movimiento" required /><select id="type" name="type" class="select-placeholder mt-1 block w-full rounded-md border-gray-300 focus:border-cyan-500 focus:ring-cyan-500" required><option value="">Seleccione un tipo</option>@foreach ($types as $type)<option value="{{ $type->value }}" @selected(old('type') === $type->value)>{{ $type->label() }}</option>@endforeach</select><x-input-error :messages="$errors->get('type')" class="mt-2" /></div><div><x-input-label for="quantity" value="Cantidad" required /><x-text-input id="quantity" name="quantity" type="number" min="0" step="any" class="mt-1 block w-full" :value="old('quantity')" required /><x-input-error :messages="$errors->get('quantity')" class="mt-2" /><p class="mt-2 text-xs text-gray-500">Las flechas avanzan por unidades; también puedes escribir hasta tres decimales.</p></div></div>
            <div><x-input-label for="reason" value="Motivo" required /><x-text-input id="reason" name="reason" type="text" class="mt-1 block w-full" :value="old('reason')" maxlength="150" required autocomplete="off" placeholder="Ej.: Entrada de mercadería" /><x-input-error :messages="$errors->get('reason')" class="mt-2" /></div>
            <div><x-input-label for="observation" value="Observación (opcional)" /><textarea id="observation" name="observation" rows="4" maxlength="1000" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-cyan-500 focus:ring-cyan-500" autocomplete="off" placeholder="Agrega contexto cuando sea necesario.">{{ old('observation') }}</textarea><x-input-error :messages="$errors->get('observation')" class="mt-2" /></div>
            <x-input-error :messages="$errors->get('product')" class="mt-2" />
            <div class="flex flex-col-reverse gap-3 border-t border-gray-100 pt-6 sm:flex-row sm:justify-end"><a href="{{ route('inventory.index') }}" class="inline-flex justify-center rounded-lg border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-50">Cancelar</a><x-primary-button>Registrar movimiento</x-primary-button></div>
        </form>
    </div></div>
</x-app-layout>
