<x-app-layout>
    <x-slot name="header"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 class="text-2xl font-semibold text-gray-900">Historial de inventario</h1><p class="mt-1 text-sm text-gray-600">Registro permanente de cambios de stock.</p></div><a href="{{ route('inventory.index') }}" class="inline-flex justify-center rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-semibold text-gray-700 hover:bg-gray-50">Volver al inventario</a></div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        @if (session('status'))<div class="mb-6 rounded-lg border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800" role="status">{{ session('status') }}</div>@endif
        <form method="GET" action="{{ route('inventory.movements.index') }}" class="mb-6 grid gap-4 rounded-xl bg-white p-4 shadow-sm ring-1 ring-gray-200 sm:grid-cols-3">
            <div class="sm:col-span-2"><x-input-label for="search" value="Buscar producto" /><x-text-input id="search" name="search" type="search" class="mt-1 block w-full" :value="$filters['search']" placeholder="Nombre o código" /></div>
            <div><x-input-label for="type" value="Tipo" /><select id="type" name="type" class="mt-1 block w-full rounded-md border-gray-300 focus:border-cyan-500 focus:ring-cyan-500"><option value="">Todos</option>@foreach ($types as $type)<option value="{{ $type->value }}" @selected($filters['type'] === $type->value)>{{ $type->label() }}</option>@endforeach</select></div>
            @if ($filters['product'])<input type="hidden" name="product" value="{{ $filters['product'] }}">@endif
            <div class="flex gap-2 sm:col-span-3 sm:justify-end"><x-primary-button>Buscar</x-primary-button><a href="{{ route('inventory.movements.index') }}" class="inline-flex items-center rounded-md border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-50">Limpiar</a></div>
        </form>
        <div class="hidden overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-gray-200 lg:block"><table class="min-w-full divide-y divide-gray-200"><thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left text-xs font-semibold uppercase text-gray-600">Fecha</th><th class="px-4 py-3 text-left text-xs font-semibold uppercase text-gray-600">Producto</th><th class="px-4 py-3 text-left text-xs font-semibold uppercase text-gray-600">Tipo</th><th class="px-4 py-3 text-right text-xs font-semibold uppercase text-gray-600">Cantidad</th><th class="px-4 py-3 text-right text-xs font-semibold uppercase text-gray-600">Anterior</th><th class="px-4 py-3 text-right text-xs font-semibold uppercase text-gray-600">Resultante</th><th class="px-4 py-3 text-left text-xs font-semibold uppercase text-gray-600">Responsable / motivo</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse ($movements as $movement)<tr><td class="whitespace-nowrap px-4 py-4 text-sm text-gray-600">{{ $movement->created_at->format('d/m/Y H:i') }}</td><td class="px-4 py-4"><div class="font-medium text-gray-900">{{ $movement->product->name }}</div><div class="text-xs text-gray-500">{{ $movement->product->displayCode() }}</div></td><td class="px-4 py-4 text-sm font-medium {{ $movement->type->increasesStock() ? 'text-green-700' : 'text-red-700' }}">{{ $movement->type->label() }}</td><td class="px-4 py-4 text-right font-semibold {{ $movement->type->increasesStock() ? 'text-green-700' : 'text-red-700' }}">{{ $movement->type->increasesStock() ? '+' : '−' }}{{ number_format((float) $movement->quantity, 3, ',', '.') }}</td><td class="px-4 py-4 text-right text-sm">{{ number_format((float) $movement->stock_before, 3, ',', '.') }}</td><td class="px-4 py-4 text-right text-sm font-semibold">{{ number_format((float) $movement->stock_after, 3, ',', '.') }}</td><td class="px-4 py-4"><div class="text-sm font-medium text-gray-900">{{ $movement->user->name }}</div><div class="text-xs text-gray-600">{{ $movement->reason }}</div>@if ($movement->observation)<div class="mt-1 text-xs text-gray-500">{{ $movement->observation }}</div>@endif</td></tr>@empty<tr><td colspan="7" class="px-6 py-12 text-center text-sm text-gray-500">No existen movimientos para los filtros seleccionados.</td></tr>@endforelse</tbody></table></div>
        <div class="space-y-4 lg:hidden">@forelse ($movements as $movement)<article class="rounded-xl bg-white p-4 shadow-sm ring-1 ring-gray-200"><div class="flex items-start justify-between gap-3"><div><h2 class="font-semibold text-gray-900">{{ $movement->product->name }}</h2><p class="text-xs text-gray-500">{{ $movement->created_at->format('d/m/Y H:i') }}</p></div><span class="font-semibold {{ $movement->type->increasesStock() ? 'text-green-700' : 'text-red-700' }}">{{ $movement->type->increasesStock() ? '+' : '−' }}{{ number_format((float) $movement->quantity, 3, ',', '.') }}</span></div><dl class="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt class="text-gray-500">Tipo</dt><dd class="font-medium">{{ $movement->type->label() }}</dd></div><div><dt class="text-gray-500">Stock</dt><dd class="font-medium">{{ number_format((float) $movement->stock_before, 3, ',', '.') }} → {{ number_format((float) $movement->stock_after, 3, ',', '.') }}</dd></div><div class="col-span-2"><dt class="text-gray-500">Motivo</dt><dd class="font-medium">{{ $movement->reason }}</dd></div>@if ($movement->observation)<div class="col-span-2"><dt class="text-gray-500">Observación</dt><dd>{{ $movement->observation }}</dd></div>@endif<div class="col-span-2"><dt class="text-gray-500">Responsable</dt><dd>{{ $movement->user->name }}</dd></div></dl></article>@empty<div class="rounded-xl bg-white p-8 text-center text-sm text-gray-500 shadow-sm ring-1 ring-gray-200">No existen movimientos.</div>@endforelse</div>
        <div class="mt-6">{{ $movements->links() }}</div>
    </div></div>
</x-app-layout>
