<x-app-layout>
    <x-slot name="header"><div class="flex justify-between"><h2 class="font-semibold text-xl text-gray-800">Venta {{ $sale->sale_number }}</h2><a href="{{ route('sales.index') }}" class="text-sm text-indigo-600">Volver al historial</a></div></x-slot>
    <div class="py-8"><div class="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 space-y-5">
        @if (session('status'))<div class="rounded-md bg-green-50 p-4 text-green-800">{{ session('status') }}</div>@endif
        <section class="grid gap-3 bg-white p-5 shadow-sm sm:rounded-lg sm:grid-cols-4"><div><small class="text-gray-500">Fecha y hora</small><p>{{ $sale->confirmed_at->format('d/m/Y H:i') }}</p></div><div><small class="text-gray-500">Cajero</small><p>{{ $sale->user->name }}</p></div><div><small class="text-gray-500">Estado</small><p>{{ $sale->status->label() }}</p></div><div><small class="text-gray-500">Forma de pago</small><p>{{ $sale->paymentLabel() }}</p></div></section>
        <section class="overflow-x-auto bg-white shadow-sm sm:rounded-lg"><table class="min-w-full divide-y"><thead class="bg-gray-50"><tr>@foreach (['Producto','Cantidad','Precio unitario','Subtotal'] as $heading)<th class="px-4 py-3 text-left text-xs uppercase text-gray-500">{{ $heading }}</th>@endforeach</tr></thead><tbody class="divide-y">@foreach ($sale->items as $item)<tr><td class="px-4 py-3"><strong>{{ $item->product_name }}</strong><small class="block text-gray-500">{{ $item->product?->displayCode() }}</small></td><td class="px-4 py-3">{{ $item->quantityLabel() }}</td><td class="px-4 py-3">Bs {{ number_format((float) $item->unit_price, 2) }}</td><td class="px-4 py-3">Bs {{ number_format((float) $item->subtotal, 2) }}</td></tr>@endforeach</tbody><tfoot><tr><td colspan="3" class="px-4 py-4 text-right text-lg font-bold">Total</td><td class="px-4 py-4 text-lg font-bold">Bs {{ number_format((float) $sale->total, 2) }}</td></tr></tfoot></table></section>
        <section class="bg-white p-5 shadow-sm sm:rounded-lg"><h3 class="font-semibold mb-3">Pagos</h3><div class="space-y-2">@foreach ($sale->payments as $payment)<div class="flex justify-between"><span>{{ $payment->method->label() }}</span><strong>Bs {{ number_format((float) $payment->amount, 2) }}</strong></div>@if ($payment->method->value === 'cash' && $payment->received_amount !== null)<div class="flex justify-between text-sm text-gray-600"><span>Recibido: Bs {{ number_format((float) $payment->received_amount, 2) }}</span><span>Cambio: Bs {{ number_format((float) $payment->change_amount, 2) }}</span></div>@endif @endforeach</div></section>
        <a href="{{ route('pos.index') }}" class="inline-block rounded-md bg-indigo-600 px-5 py-3 text-white">Nueva venta</a>
    </div></div>
</x-app-layout>
